<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="../../css/style.css">
    <title>Document</title>
  <script>
      //check wether the fields have been filled or not, if they are empty send error message to user
      function checkIfFieldsEmpty() {
    let fullname = document.forms["myForm"]["fullname"].value;
    let username = document.forms["myForm"]["username"].value;
    let image = document.forms["myForm"]["image"].value;
    let email = document.forms["myForm"]["email"].value;
    let pass = document.forms["myForm"]["password"].value;
    if (fullname == "" || username == "" || image == "" || email == "" || pass == "") {
      alert("all fields must be filled");
      return false;
    }
  }
  </script>
</head>
<body>
<div class="signup-form">
    <div class="container-fluid d-flex justify-content-center align-items-center h-100">
        <div class="p-3 text-center py-4">
            <h4>Create account</h4>
            <div> <span>Already have an account?</span> <a href="../index.php" class="text-decoration-none">Login</a> </div>
            <form name="myForm" method="post" action="../signup.php" enctype="multipart/form-data" onsubmit="return checkIfFieldsEmpty()">
            <div class="mt-3 px-3"> <input type="text" name="fullname" class="form-control" placeholder="Full Name" > </div>
            <div class="mt-3 px-3"> <input type="text" name="username" class="form-control" placeholder="Username" > </div>
            <div class="mt-3 px-3"> <input type="file" accept="image/*" name="image"class="form-control form-control-lg" id="formFile" ></div>
            <div class="mt-3 px-3"> <input type="email"name="email"class="form-control" placeholder="E-mail" > </div>
            <div class="mt-3 px-3"> <input type="password" name="password" class="form-control" id="signup-Password" placeholder="Password"></div>
            <div class="mt-3 d-grid px-3"> <button type="submit" name="signupbutton" value="Signup" class="btn btn-primary btn-block btn-signup text-uppercase"> <span>Signup</span> </button> </div>
            </form>
        
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>