<?php require('Views/template/loginmodal.phtml') ?>
<?php require('Views/template/logoutmodal.phtml') ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Ayub">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="js/OpenLayers-2.13.1/OpenLayers.js"></script>
    <script src="js/location.js"></script>
    <title>FriendLocator - <?php echo $view->pageTitle; ?></title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">FriendLocator</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="index.php">Home</a>
                </li>
                <?php
                if (!isset($_SESSION["login"])) //if login session doesn't exist/if the user is not logged in
                {
                  echo ' 
                    <li class="nav-item">
                      <a class="nav-link btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Login</a>
                    </li>';
                }
                else {
                    echo '
                     <li class="nav-item">
                       <a class="nav-link" href="friends.php">Friends</a>
                     </li>
                     <li class="nav-item">
                       <a class="nav-link btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#exampleModal2">Logout</a>
                     </li>';
                }
                ?>
                 <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="../clientserversys/self-assessment.pdf">self-assessment</a>
                </li>
            </ul>
            
        </div>
    </div>
</nav>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>



