<div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="Modal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" action="index.php">
            <div class="modal-header">
                <h5 class="modal-title">Logout</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p class="text-center">Are you sure you want to logout?</p>
            </div>
            <div class="modal-footer pt-4">
            <button type="submit" name="logoutbutton" value="Logout" class="btn btn-danger mx-auto w-100">Logout</button>
            </div>
            </form>
        </div>
    </div>
</div>
